# Check https://circleci.com/docs/2.0/language-clojure/ for more details
version: 2
jobs:

  test:
    docker: 
      - image: vitorqb23/rappelle-be-ci:4
    steps:
      - checkout
      - run:
          name: Install sbt
          command: sbt sbtVersion
      - run:
          name: Run Unit Tests
          command: rappelle-be-tools test

  scalafmt:
    docker:
      - image: vitorqb23/rappelle-be-ci:4
    steps:
      - checkout
      - run:
          name: Scalafmt check
          command: rappelle-be-tools scalafmt --check

  funTest:
    machine: 
      image: ubuntu-2004:202010-01
    steps:
      - run:
          name: Setup Environment Variables
          command: |
            echo "export PATH=${HOME}/.local/bin:${HOME}/rappelledev:$(pwd)/dev:$PATH" | tee -a $BASH_ENV
      - checkout
      - run:
          name: Install rappelledev.py
          command: ./.circleci/rappelledev/install.bash
      - run:
          name: Install docker-compose
          command: ./.circleci/docker-compose/install.bash
      - run:
          name: Start container for Postgres
          command: |
            rappelledev.py run-postgres -- --detach
            sleep 3
            rappelledev.py docker-compose -- logs
      - run:
          name: Starts container for functional tests
          command: |
            docker run \
              -dti \
              -v "$(pwd):/root/project" \
              --name funtest \
              --entrypoint='/bin/bash' \
              --network=host \
              "vitorqb23/rappelle-be-ci:4"
      - run:
          name: Installs sbt (in container)
          command: >-
            docker exec funtest bash -c 'cd /root/project && sbt sbtVersion'
      - run:
          name: Run functional tests (in container)
          command: docker exec funtest rappelle-be-tools test --functional


workflows:
  version: 2
  test:
    jobs:
      - test: {}
      - funTest: {}
      - scalafmt: {}
