version: "3.7"
services:
  postgres:
    ports:
      - "5000:5432" 
    volumes:
      - pgdata-rappelle-be-local:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=theuser
      - POSTGRES_PASSWORD=thepassword
volumes:
  pgdata-rappelle-be-local:
